[project]
name = "eggsactly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "csbdeep==0.8.2",
    "numpy==2.3.5",
    "opencv-python==4.13.0.92",
    "scikit-image==0.26.0",
    "scipy==1.17.0",
    "stardist==0.9.2",
    "torch>=2.10.0",
    "tqdm==4.65.0",
]
